name: custom_error
description: The "custom_error" library is a powerful flutter package designed to streamline error management and elevate error handling in your flutter applications.
version: 0.0.6
homepage: https://github.com/youngcet/custom_error

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.1
  ndialog: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
